### ISSUE TITLE
TooManyProviderTokenUpdates

### ISSUE THREAD

**Issue by superk589** [Lyle-Du/Swifty-Pusher#3]
Error Snapshot:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/19667784/173725993-ba34616e-7fab-452e-b196-d278a68c68e3.png">
According to https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/handling_notification_responses_from_apns
429 | TooManyProviderTokenUpdates | The provider’s authentication token is being updated too often. Update the authentication token no more than once every 20 minutes.
-- | -- | --

Reproduce Steps:
Send the same notification to the same device 3-5 times continuously.

**Comment by Lyle-Du** [comment]
Hi @superk589 
Thanks for the feedback. This issue is fixed in [1cd69d2](https://github.com/Lyle-Du/Swifty-Pusher/commit/1cd69d2fd33b1784aa3dfa3a7dcd842956b6307c)
;)
